Repository Romsou/System-Project, pull requests merged in 2021-01, with the labels that each got.

#3 Note addition
  doc/rapport.txt
Labels: documentation

#4 Addition of documentation
  doc/general/Soutenances_NACHOS_2010_2011.key.pdf
  doc/general/presentation.pdf
  doc/report.txt
  doc/step-1/etape1.pdf
  doc/step-2/ETAPE2_2011.pdf
  doc/step-2/etape2.pdf
  doc/step-2/nachos-syscall.pdf
Labels: documentation

#5 Rearrangement of doc
  doc/Project-READMEs/README
  doc/Project-READMEs/README.Debian
  doc/Project-READMEs/README.old
  doc/Project-READMEs/nachos.ps.gz
  doc/Report/report.txt
Labels: documentation

#17 SynchPutChar done
  code/userprog/synchconsole.cc
Labels: enhancement

#18 Step2, SynchPutString + Makefile synchConsole
  code/Makefile.define-user
  code/userprog/synchconsole.cc
Labels: Step 2, enhancement

#21 SynchGetString
  code/userprog/synchconsole.cc
Labels: Step 2, enhancement

#19 Jah dev
  code/Makefile.define-user
  code/userprog/progtest.cc
  code/userprog/synchconsole.cc
Labels: Step 2, documentation, enhancement

#24 Jah dev
  code/Makefile.define-user
  code/threads/system.cc
  code/threads/system.h
  code/userprog/progtest.cc
Labels: enhancement

#25 Clery add SynchConsoleTest
  code/Makefile.define-user
  code/threads/main.cc
  code/userprog/progtest.cc
Labels: Step 2, enhancement

#27 Clery, report step2, Day 2
  code/Makefile.define-user
  code/test/putchar.c
  code/test/start.S
  code/threads/main.cc
  code/threads/system.cc
  code/threads/system.h
  code/userprog/progtest.cc
  code/userprog/synchconsole.cc
  code/userprog/synchconsole.h
  code/userprog/syscall.h
  doc/step-2/Step2_rapport
Labels: documentation

#26 Addtion of test for synchconsole
  code/test/test_synchconsole_file.sh
Labels: Step 2, enhancement, test

#29 Creation of a switch in the exception handler
  code/userprog/exception.cc
Labels: Step 2, enhancement

#31 Moved handler functions for declaration scope
  code/userprog/exception.cc
Labels: enhancement

#33 Addition of copyStringFromMachine()
  code/userprog/exception.cc
Labels: Step 2, enhancement

#38 Jah dev
  code/test/putchar.c
  code/userprog/exception.cc
  doc/Report/report_step2.md
Labels: Step 2, enhancement, test

#40 Fix unsigned and int comparison
  code/userprog/exception.cc
Labels: enhancement

#41 Fix of the synchconsole bug
  code/userprog/progtest.cc
Labels: Step 2, fix

#42 Clery, PutString + fix putChar + fix copyStringFromMachine
  code/test/putstring.c
  code/test/start.S
  code/threads/system.h
  code/userprog/exception.cc
  code/userprog/progtest.cc
  code/userprog/syscall.h
  doc/step-2/Step2_rapport
Labels: enhancement

#45 SynchConsole: It just works
  code/threads/system.cc
Labels: Step 2, fix

#48 Part 6 - Stopping a program [Jah]
  code/test/putchar.c
  code/test/start.S
  code/userprog/exception.cc
  code/userprog/syscall.h
  doc/Report/report_step2.md
  doc/Report/report_step3.txt
Labels: enhancement

#49 PutInt and GetInt added
  code/test/getint.c
  code/test/putint.c
  code/test/start.S
  code/userprog/exception.cc
  code/userprog/syscall.h
Labels: enhancement

#47 Appel systeme getstring + ajout d'un lock dans synchgetstring
  code/test/start.S
  code/userprog/exception.cc
  code/userprog/synchconsole.cc
  code/userprog/syscall.h
Labels: Step 2, enhancement

#50 Report of the day
  doc/Report/improvements.md
  doc/Report/report.txt
  doc/step-2/Step2_rapport
Labels: Step 2, documentation

#53 comments + little fix
  code/threads/main.cc
  code/userprog/exception.cc
  code/userprog/progtest.cc
  code/userprog/synchconsole.cc
  code/userprog/syscall.h
Labels: documentation

#54 Doc for step 3
  doc/general/roadmap.pdf
  doc/step-3/ETAPE3.pdf
  doc/step-3/etape3.pdf
Labels: Step 3, documentation

#62 Addition of minunit for unit testing
  code/test/minunit.h
Labels: enhancement

#63 Fix getString + add handlerGetString + comments
  code/test/getint.c
  code/test/getstring.c
  code/test/putint.c
  code/test/putstring.c
  code/userprog/exception.cc
  code/userprog/syscall.h
Labels: enhancement, fix

#67 Several fixes
  code/threads/system.cc
  code/userprog/exception.cc
  code/userprog/progtest.cc
Labels: Step 2, Step 3, fix

#70 part1 skeleton + makefile
  code/Makefile.define-user
  code/test/start.S
  code/threads/system.cc
  code/userprog/exception.cc
  code/userprog/syscall.h
  code/userprog/userthread.cc
  code/userprog/userthread.h
Labels: enhancement

#71 StartUserThreadCreate() and a few fixes
  code/userprog/exception.cc
  code/userprog/syscall.h
  code/userprog/userthread.cc
  code/userprog/userthread.h
Labels: Step 3, enhancement, fix

#72 Doc and fixes
  code/userprog/exception.cc
  code/userprog/userthread.cc
Labels: Step 3, documentation, fix

#73 First uncompletely working version of StartUserThread
  code/test/userthreadcreateV2.c
  code/userprog/exception.cc
  code/userprog/userthread.cc
Labels: Step 3, bug, enhancement

#74 Wassim dev
  code/test/start.S
  code/test/userThreadCreate.c
  code/test/userthreadcreateV2.c
  code/threads/thread.h
  code/userprog/exception.cc
  code/userprog/syscall.h
  code/userprog/userthread.cc
  code/userprog/userthread.h
Labels: Step 3, enhancement

#75 StartUserThread finally done
  code/test/userthreadcreateV2.c
  code/userprog/userthread.cc
  code/userprog/userthread.h
Labels: Step 3, documentation, enhancement, fix

#78 add semaphore for thread with same adrrSpace (but unused), add synchConsole critical section for all calls. handle case where a thread call halt while all userthread are not properly exited.
  code/test/userThreadCreate.c
  code/test/userthreadcreate.c
  code/test/userthreadcreateV2.c
  code/threads/system.h
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
  code/userprog/exception.cc
  code/userprog/synchconsole.cc
  code/userprog/synchconsole.h
  code/userprog/syscall.h
  code/userprog/userthread.cc
  code/userprog/userthread.h
Labels: Step 3, enhancement

#87 Documentation of SynchConsole and indentation
  code/userprog/exception.cc
  code/userprog/synchconsole.cc
  code/userprog/synchconsole.h
  code/userprog/userthread.cc
  code/userprog/userthread.h
  doc/Report/report.txt
Labels: Step 3, documentation, fix

#89 Documentation of userthread module
  code/userprog/userthread.cc
  code/userprog/userthread.h
Labels: Step 3, documentation

#90 Doc userthread.h
  code/userprog/userthread.h
Labels: Step 3, documentation

#92 Modification of list
  code/threads/list.cc
  code/threads/list.h
  code/threads/scheduler.cc
  code/threads/scheduler.h
  code/userprog/userthread.cc
Labels: Step 3, enhancement

#95 Fix synchro Halt/exit + add/rename/fix tests + synchConsole critical sections now works with only one semaphore + fix (may be) stackReg in StartUserThread
  code/test/userthreadcreateV0.c
  code/test/userthreadcreateV1.c
  code/test/userthreadcreateV2.c
  code/test/userthreadcreateV3.c
  code/threads/thread.cc
  code/threads/thread.h
  code/userprog/addrspace.h
  code/userprog/exception.cc
  code/userprog/synchconsole.cc
  code/userprog/userthread.cc
  doc/step-3/synchro_threads
Labels: Step 3, fix

#96 New test
  code/test/userthreadcreate_limitOfThread.c
Labels: Step 3, test

#97 Modify manythreads tests
  code/test/userthreadcreate_automaticend.c
  code/test/userthreadcreate_fewthreads.c
  code/test/userthreadcreate_join.c
  code/test/userthreadcreate_manythreads.c
Labels: fix

#104 fix synchro issue in synchConsole
  code/test/getchar.c
  code/userprog/synchconsole.cc
  doc/step-3/synchro_synchConsole
Labels: fix

#105 fix handlePutString with real size
  code/userprog/exception.cc
Labels: fix

#106 remove last fix + modify MAX_STRING_SIZE
  code/userprog/exception.cc
Labels: fix

#108 Improvement of synchconsole.cc
  code/userprog/synchconsole.cc
Labels: Step 1, enhancement

#114 Fix P/V -> synchro Halt/exit + move ListOfUserThread in addrSpace.h + ReadAtVirtual
  code/filesys/openfile.h
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
  code/userprog/exception.cc
  code/userprog/userthread.cc
Labels: enhancement, fix

#117 synchConsole synchro + modify test : Halt replaced by End
  code/test/userthreadcreate_automaticend.c
  code/test/userthreadcreate_fewthreads.c
  code/test/userthreadcreate_join.c
  code/test/userthreadcreate_manythreads.c
  code/userprog/synchconsole.cc
  code/userprog/synchconsole.h
Labels: fix

#121 Remove BitMap + add userThread list in addrSpace and related function and then modify userthread.cc and exception.cc
  code/threads/system.h
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
  code/userprog/exception.cc
  code/userprog/userthread.cc
  code/userprog/userthread.h
Labels: Step 3, enhancement, fix

#126 fix one gettid ->getIndex
  code/threads/thread.cc
  code/userprog/exception.cc
  code/userprog/userthread.cc
Labels: fix

#129 fix join
  code/test/userthreadcreate_manythreads.c
  code/userprog/addrspace.cc
  code/userprog/userthread.cc
Labels: Step 3, fix

#130 Correction of the semaphore system in threads
  code/test/userpages0.c
  code/test/userthreadcreate_automaticend.c
  code/test/userthreadcreate_limitOfThread.c
  code/threads/thread.cc
  code/threads/thread.h
  code/userprog/addrspace.cc
  code/userprog/userthread.cc
Labels: Step 3, fix

#131 fix manythreads test
  code/test/userthreadcreate_manythreads.c
Labels: Step 3, fix

#133 Merge Dev up until step 3 in master
  code/Makefile.define-user
  code/filesys/openfile.cc
  code/network/post.cc
  code/test/getchar.c
  code/test/getint.c
  code/test/getstring.c
  code/test/minunit.h
  code/test/putchar.c
  code/test/putint.c
  code/test/putstring.c
  code/test/start.S
  code/test/test_synchconsole_file.sh
  code/test/userpages0.c
  code/test/userthreadcreate_automaticend.c
  code/test/userthreadcreate_fewthreads.c
  code/test/userthreadcreate_join.c
  code/test/userthreadcreate_limitOfThread.c
  code/test/userthreadcreate_manythreads.c
  code/threads/list.cc
  code/threads/list.h
  code/threads/main.cc
  code/threads/scheduler.cc
  code/threads/scheduler.h
  code/threads/synch.h
  code/threads/system.cc
  code/threads/system.h
  code/threads/thread.cc
  code/threads/thread.h
  code/threads/threadtest.cc
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
  code/userprog/bitmap.cc
  code/userprog/bitmap.h
  code/userprog/exception.cc
  code/userprog/frameprovider.h
  code/userprog/progtest.cc
  code/userprog/synchconsole.cc
  code/userprog/synchconsole.h
  code/userprog/syscall.h
  code/userprog/userthread.cc
  code/userprog/userthread.h
  doc/Report/improvements.md
  doc/Report/report.txt
  doc/Report/report_step2.md
  doc/Report/report_step3.txt
  doc/Report/report_step4.txt
  doc/Report/schemas/chargement_uni_process.png
  doc/Report/schemas/chargement_uni_process.xml
  doc/Report/schemas/espace_adressage.png
  doc/Report/schemas/espace_adressage.xml
  doc/Report/schemas/stack_structure.drawio.xml
  doc/Report/schemas/stack_structure.png
  doc/general/roadmap.pdf
  doc/step-2/Step2_rapport
  doc/step-3/ETAPE3.pdf
  doc/step-3/etape3.pdf
  doc/step-3/synchro_synchConsole
  doc/step-3/synchro_threads
  doc/step-4/ETAPE4_2012.pdf
  doc/step-4/etape4.pdf
Labels: Step 1, Step 2, Step 3, documentation, enhancement

#136 Non misleading names
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
  code/userprog/userthread.cc
Labels: Step 3, documentation, enhancement

#135 step4 part I.1 -> I.4 (frameprovider class skeleton + ReadAtVirtual) + MAKEFILE UPDATE + fix test userpages0
  code/Makefile.define-user
  code/test/userpages0.c
  code/userprog/addrspace.cc
  code/userprog/frameprovider.cc
  code/userprog/frameprovider.h
Labels: Step 4, enhancement

#137 FrameProvider implementation
  code/userprog/frameprovider.cc
  code/userprog/frameprovider.h
Labels: Step 4, enhancement

#138 fix frameprovider
  code/userprog/frameprovider.cc
  code/userprog/frameprovider.h
Labels: Step 4, fix

#139 Memory working
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
  code/userprog/frameprovider.cc
  code/userprog/frameprovider.h
Labels: Step 4, enhancement

#140 Memory implemented and documented
  code/userprog/frameprovider.cc
  code/userprog/frameprovider.h
Labels: Step 4, documentation, enhancement

#146 mv frameprovider into system.h
  code/threads/system.cc
  code/threads/system.h
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
Labels: Step 4, enhancement

#147 Addrspace 21st century edition
  code/bin/noff.h
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
Labels: Step 3, Step 4, Step 5, Step 6, documentation, enhancement

#154 Creation of process table
  code/threads/thread.cc
  code/threads/thread.h
  code/userprog/processtable.cc
  code/userprog/processtable.h
Labels: Step 4, documentation, enhancement

#155 synchro between processes + handle processTable + fix process Table
  code/Makefile.define-user
  code/machine/machine.h
  code/test/userpages0.c
  code/test/userpages1.c
  code/threads/system.cc
  code/threads/system.h
  code/threads/thread.cc
  code/threads/thread.h
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
  code/userprog/exception.cc
  code/userprog/processtable.cc
  code/userprog/processtable.h
  code/userprog/systemthread.cc
Labels: Step 4, enhancement, fix

#158 fix frameprovider ReleaseFrame + modify ~addrSpace in order to remove…
  code/userprog/addrspace.cc
  code/userprog/frameprovider.cc
Labels: enhancement, fix

#156 Documentation update
  code/threads/thread.h
  code/userprog/userthread.cc
  code/userprog/userthread.h
  doc/Report/schemas/Process_table.png
  doc/Report/schemas/Process_table.xml
Labels: Step 3, documentation

#160 Clery
  code/test/userpages1.c
  code/threads/system.cc
  code/threads/system.h
  code/threads/thread.cc
  code/threads/thread.h
  code/userprog/processtable.cc
  code/userprog/processtable.h
  code/userprog/systemthread.cc
  code/userprog/userthread.cc
Labels: Step 4, enhancement, fix

#161 Ability to read and write from and to file restored
  code/threads/system.cc
  code/userprog/exception.cc
  code/userprog/syscall.h
Labels: Step 2, fix

#162 test 12threads/
  code/machine/machine.h
  code/test/process_12processes.c
  code/test/process_12threads.c
  code/userprog/addrspace.h
  code/userprog/exception.cc
Labels: Step 4, enhancement

#163 Fixed misleading name
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
  code/userprog/exception.cc
Labels: Step 4, fix

#165 fix setTid
  code/threads/thread.cc
Labels: fix

#166 Fix memory leak
  code/userprog/systemthread.cc
Labels: Step 4, fix

#167 fix delete in processTable
  code/userprog/processtable.cc
Labels: fix

#168 Non-automated integration tests
  code/test/test_processes.sh
  code/test/test_userthreads.sh
Labels: Step 4, test

#171 Merge step 4
  .github/pull_request_template.md
  code/Makefile.define-user
  code/bin/noff.h
  code/machine/machine.h
  code/test/process_12processes.c
  code/test/process_12threads.c
  code/test/process_forkexec.c
  code/test/shell_V2.c
  code/test/start.S
  code/test/test_processes.sh
  code/test/test_synchconsole_file.sh
  code/test/test_userthreads.sh
  code/test/userpages0.c
  code/test/userpages1.c
  code/threads/system.cc
  code/threads/system.h
  code/threads/thread.cc
  code/threads/thread.h
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
  code/userprog/bitmap.cc
  code/userprog/exception.cc
  code/userprog/frameprovider.cc
  code/userprog/frameprovider.h
  code/userprog/processtable.cc
  code/userprog/processtable.h
  code/userprog/progtest.cc
  code/userprog/syscall.h
  code/userprog/systemthread.cc
  code/userprog/systemthread.h
  code/userprog/userthread.cc
  code/userprog/userthread.h
  doc/Report/report_step4.txt
  doc/Report/schemas/Allocation_mem_process.png
  doc/Report/schemas/Process_table.png
  doc/Report/schemas/Process_table.xml
  doc/step-5/etape5.pdf
  doc/step-6/etape6.pdf
Labels: Step 4, enhancement

#174 Modifcation of Makefile
  code/Makefile.define-user
Labels: Step 6

#180 Ring topology test made
  code/test/nettest_modified.cc
  code/test/network_machine_ring.cc
  code/test/test_network_machine_ring.sh
  code/threads/system.cc
  code/threads/system.h
Labels: Step 6, test

#182 Step5 part1, handle path in createDir + removeDir + changeDir + add some function to handle path + add lock from romain
  code/filesys/directory.cc
  code/filesys/filesys.cc
  code/filesys/filesys.h
  code/filesys/fsconsole.cc
  code/threads/synch.cc
  code/threads/synch.h
Labels: Step 5, enhancement

#184 handle path in create/file/open + fix comments
  code/filesys/filesys.cc
  code/filesys/filesys.h
Labels: Step 5, enhancement, fix

#185 Clery s5 dev
  code/filesys/directory.cc
  code/filesys/filesys.cc
Labels: Step 5, fix

#186 Function Close Added
  code/filesys/directory.cc
  code/filesys/filesys.cc
  code/filesys/filesys.h
  doc/Report/report_step5.txt
Labels: enhancement, question

#187 Step 5 , part II, handle system opened file table. add files filetable.h/.cc + modify filesys.cc
  code/Makefile.define-user
  code/filesys/directory.cc
  code/filesys/filesys.cc
  code/filesys/filesys.h
  code/filesys/filetable.cc
  code/filesys/filetable.h
  code/threads/main.cc
Labels: Step 5, enhancement

#192 try to handle filesys system calls + file test create filesys
  code/filesys/directory.h
  code/filesys/filesys.cc
  code/filesys/filesys.h
  code/filesys/filetable.cc
  code/filesys/filetable.h
  code/test/filesys_create.c
  code/userprog/exception.cc
Labels: Step 5, enhancement

#189 Synchronization update
  code/test/test_network_machine_ring.sh
  code/threads/list.h
  code/threads/scheduler.cc
  code/threads/scheduler.h
  code/threads/synch.cc
  code/threads/synch.h
  code/threads/synchlist.cc
  code/threads/synchlist.h
  code/threads/system.cc
  code/threads/thread.cc
  code/threads/thread.h
Labels: Step 6, enhancement

#195 working test for filesys
  code/filesys/filesys.cc
  code/filesys/filetable.cc
  code/test/filesys_create.c
  code/test/filesys_readwrite.c
  code/test/filesys_writeread.c
  code/threads/thread.cc
  code/threads/thread.h
  code/userprog/exception.cc
  code/userprog/progtest.cc
  code/userprog/systemthread.cc
Labels: Step 5, enhancement

#200 fix file system + test + remove syscall
  code/filesys/filesys.cc
  code/filesys/filesys.h
  code/filesys/filetable.cc
  code/test/copy_exec_into_filesys.sh
  code/test/filesys_create.c
  code/test/filesys_readwrite.c
  code/test/filesys_userthread.c
  code/test/filesys_writeread.c
  code/test/start.S
  code/threads/thread.cc
  code/userprog/exception.cc
  code/userprog/syscall.h
  code/userprog/systemthread.cc
Labels: Step 5, enhancement, fix

#198 Revamped thread class
  code/test/test_processes.sh
  code/test/test_synchconsole_file.sh
  code/test/test_userthreads.sh
  code/threads/thread.cc
  code/threads/thread.h
Labels: enhancement

#204 Include step 6
  code/Makefile.define-user
  code/machine/sysdep.cc
  code/test/nettest_modified.cc
  code/test/network_machine_ring.cc
  code/test/test_network_machine_ring.sh
  code/test/test_processes.sh
  code/test/test_synchconsole_file.sh
  code/test/test_userthreads.sh
  code/threads/list.h
  code/threads/main.cc
  code/threads/scheduler.cc
  code/threads/scheduler.h
  code/threads/synch.cc
  code/threads/synch.h
  code/threads/synchlist.cc
  code/threads/synchlist.h
  code/threads/system.cc
  code/threads/system.h
  code/threads/thread.cc
  code/threads/thread.h
Labels: Step 6, documentation, enhancement

#209 Makefile + fix userthreadjoin
  code/Makefile.define-user
  code/test/userthreadcreate_join.c
  code/userprog/addrspace.cc
  code/userprog/addrspace.h
  code/userprog/exception.cc
  doc/Report/report_step5.txt
Labels: enhancement, fix, test

#213 rename files + step6 now compile without filesys
  code/Makefile.define-user
  code/filesys/directory.h
  code/test/thread_automaticend.c
  code/test/thread_fewthreads.c
  code/test/thread_join.c
  code/test/thread_limitOfThread.c
  code/test/thread_manythreads.c
Labels: fix

#215 fix addrspace main stack -> fix fewThread
  code/test/thread_fewthreads.c
  code/test/userthreadcreate_limitOfThread.c
  code/userprog/addrspace.h
  code/userprog/userthread.cc
Labels: fix

#221 halt if create process when no more spacein physical memory
  code/userprog/addrspace.cc
  code/userprog/systemthread.cc
Labels: bug, fix

#222 better tests + fix negative number + fix End+UTC_Exit+ForkExec call by process or thread + handle thread open file table
  code/test/process_12processes.c
  code/test/process_12threads.c
  code/test/process_forkexec.c
  code/test/thread_automaticend.c
  code/test/userpages0.c
  code/test/userpages1.c
  code/threads/system.h
  code/userprog/exception.cc
  code/userprog/systemthread.cc
  code/userprog/userthread.cc
Labels: fix

#225 fix getString max len
  code/userprog/synchconsole.cc
Labels: fix
